started writing reports. need to fix issue of splitting up code into modules: ImportError: cannot import name 'teams' from partially initialized module 'teams_list' (most likely due to a circular import)